# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install'

- script: |
    npm run build
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'

- script: |
    npm run lint
  condition: succeededOrFailed()
  displayName: 'Lint'

- script: |
    npm run test:unit
  condition: succeededOrFailed()
  displayName: 'Unit Test'

- script: |
    npm run test:ci
  condition: succeededOrFailed()
  displayName: 'E2E Test'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    mergeTestResults: true
    testRunner: JUnit
    testResultsFiles: '**/test-*.xml'